### ISSUE TITLE
fail to run a docker hanlder

### ISSUE THREAD

**Issue by drev74** [choria-io/asyncjobs#73]
I'm trying to run a demo handler following [this](https://github.com/choria-io/asyncjobs/wiki/Running-in-Docker). Getting the following error: `Choria Async Jobs Handler Failed: only states completed, expired or terminated can be discarded`

To reproduce:
1. Created a NATS context with this: `XDG_CONFIG_HOME=`pwd` nats context add AJ_API --server nats://hyp:4222`
2. `chmod 777 -R ./nats`
3. `docker run -it -v $PWD/nats:/handler/config/nats -e AJ_NATS_CONTEXT=AJ_API -p 8087:8080 --rm xxxx/asynq:test`

Container failed to start with the following:
```bash
docker run -it -v $PWD/nats:/handler/config/nats -e AJ_NATS_CONTEXT=AJ_API -p 8087:8080 --rm
 xxxx/asynq:test                                                                                                                                           
INFO[13:21:22] Choria Async Jobs Handler Service git.example.com/example build settings                                                                       
INFO[13:21:22] NATS Context: AJ_API                                                                                                                           
INFO[13:21:22] Work Queue: SDK                                                                                                                                
INFO[13:21:22] Concurrency: 12                                                                                                                                
INFO[13:21:22] Retry Policy: 1m                                                                                                                               
INFO[13:21:22] Discard State: completed                                                                                                                       
INFO[13:21:22] Prometheus Port: 8080                                                                                                                          
Choria Async Jobs Handler Failed: only states completed, expired or terminated can be discarded  
```
OS: Ubuntu 21.10
AJ: v0.0.7

**Comment by drev74** [comment]
Sure, I use [this](https://gist.github.com/drev74/b2aadbe725937505b231309df5c806b4) and got [this](https://gist.github.com/drev74/94957d605179923aed7724d8b86c19f5)

**Comment by ripienaar** [comment]
OK, I found a bug, you can patch the generated `main.go` like this:

```
                aj.DiscardTaskStates(aj.TaskStateCompleted),
```

instead of the 
```
                aj.DiscardTaskStates("completed"),
```

that's there now - this should resolve it till I can fix it, I introduced a recent bug it seems.

**Comment by ripienaar** [comment]
In the main.go where you run docker build

**Comment by drev74** [comment]
Here's my `./nats/context/AJ_API.json`:
```json
{
  "description": "",
  "url": "nats://t.t.t.t:4222",
  "token": "",
  "user": "",
  "password": "",
  "creds": "",
  "nkey": "",
  "cert": "",
  "key": "",
  "ca": "",
  "nsc": "",
  "jetstream_domain": "",
  "jetstream_api_prefix": "",
  "jetstream_event_prefix": "",
  "inbox_prefix": ""
}
```
Then I do the same:
```bash
docker run -it -v $PWD/nats:/handler/config/nats -e AJ_NATS_CONTEXT=AJ_API -p 8087:8080 --rm
 tampler/asynq:test                                                            
INFO[14:46:05] Choria Async Jobs Handler Service git.example.com/example build settings 
INFO[14:46:05] NATS Context: AJ_API                                  
INFO[14:46:05] Work Queue: SDK                               
INFO[14:46:05] Concurrency: 12                                   
INFO[14:46:05] Retry Policy: 1m                              
INFO[14:46:05] Prometheus Port: 8080                         
Choria Async Jobs Handler Failed: nats: no responders available for request
```
So I can't run your hello-world with a changed task type from your example

**Comment by drev74** [comment]
I added a PR and my installation guide [here](https://github.com/drev74/asyncjobs/blob/pingpong/examples/pingpong/README.md)

**Comment by ripienaar** [comment]
The docker main.go thing is resolved by https://github.com/choria-io/asyncjobs/pull/75, leaving open for the discussion around starting JetStream

**Comment by drev74** [comment]
@ripienaar Hello!

1. Updated my #74 as per your request
2. Still can't make it work a Dockerized handler on my Ubuntu 21.10. I created a [demo](https://github.com/drev74/aj-handler-demo) project. Could you pls take a look :eyes: 

Still getting `Choria Async Jobs Handler Failed: nats: no responders available for request`

**Comment by ripienaar** [comment]
So still somehow it’s talking to a nats server or account without jetstream enabled. 

If the ajc commands to create queues pass but the container fails then it’s a case of the container is not talking to the correct nats server. 

Do you have any other nats server running? Anything in docker left over perhaps? Does running main.go work but docker doesn’t?

wirh the ajc commands succeeding you for the right stuff we just need to see why docker can’t get to it so I am afraid I need some more info about your env

**Comment by drev74** [comment]
Yes, I'm able to run `main.go` locally with this:
```bash
AJ_WORK_QUEUE=SDK AJ_NATS_CONTEXT=AJC go run -v main.go
INFO[15:01:27] Choria Async Jobs Handler Service github.com/drev74/aj-handler-demo build settings 
INFO[15:01:27] NATS Context: AJC                            
INFO[15:01:27] Work Queue: SDK                              
INFO[15:01:27] Concurrency: 12                              
INFO[15:01:27] Retry Policy: 1m                             
INFO[15:01:27] Prometheus Port: 8080                        
WARN[15:01:27] Exposing Prometheus metrics on port 8080      queue=SDK
ERRO[15:01:27] Could not start Prometheus listener on 8080: listen tcp :8080: bind: address already in use  queue=SDK
```

**Comment by drev74** [comment]
And here's my JetStream setup:
```bash
curl -v telnet://0.0.0.0:34377                                                                                           ✔  10327  13:58:45
*   Trying 0.0.0.0:34377...
* Connected to 0.0.0.0 (127.0.0.1) port 34377 (#0)
INFO {"server_id":"NDZJS7ZKJ4CNNDNL3UPOPPQLOEQQF6WAPSUJHYLSB2ZY4ZQ424KAZZHR","server_name":"AJC","version":"2.8.0-beta.22","proto":1,"go":"go1.18.1","host":"0.0.0.0","port":34377,"headers":true,"auth_required":true,"max_payload":1048576,"jetstream":true,"client_id":50,"client_ip":"127.0.0.1"} 
hello
-ERR 'Authentication Timeout'
```

**Comment by ripienaar** [comment]
Ah, this this. In the AJC.json change 0.0.0.0 to the up address of your Ethernet card before starting the container.

**Comment by drev74** [comment]
Could you pls checkout my [demo](https://github.com/drev74/aj-handler-demo) and run it in your env? :thinking:

**Comment by ripienaar** [comment]
You need to change this:

“url": "nats://0.0.0.0:34377"

To the IP of your machine so the comms from docker works

**Comment by drev74** [comment]
Oh, yes! That made a trick. Had to change IP to “url": "nats://192.168.1.93:34377" to make it work.

With that, I was able to reproduce your video example and will add this to wiki.

Thanks a lot for your support !
